### ISSUE TITLE
Removed drafting view

### ISSUE THREAD

**Issue by MariyanSlesar** [StudyCenterParametric/VDC_Conduits#12]
Коли користувач видаляє drafting view, то він не може потім його перезавантажити

**Comment by StudyCenterParametric** [comment]
Коли користувач видаляє Drafting View, потрібно заново його перезавантажити так як це робиться з самого початку.
Захист (від Дурня) від випадкового видалення, можна зробити?

**Comment by StudyCenterParametric** [comment]
і помилка коли ми повторно завантажуємо Ексель, якщо Вигляд був видалений 
![image](https://user-images.githubusercontent.com/102672070/165114853-3490511e-51e7-4a71-b5af-27d102540342.png)
