### ISSUE TITLE
Зєднати команди Rolling Offset i Kickoff в 1 кнопку

### ISSUE THREAD

**Issue by StudyCenterParametric** [StudyCenterParametric/VDC_Conduits#37]
Зєднати команди Rolling Offset i Kickoff в 1 кнопку, програма по правилах сама буде розбирати де який інструмент має бути. Це зменшить к-сть кнопок на плагіні в 2 рази, а відповідно і час на використання команд.

**Comment by StudyCenterParametric** [comment]
![image](https://user-images.githubusercontent.com/102672070/165131097-3dc02340-391b-4f2b-812c-394a9245fb76.png)

**Comment by MariyanSlesar** [comment]
-якщо паралельні - кути однакові з двох сторін + може висота бути як однакова так і різна
-якщо розміщення під 90 градусів - в першому елементі змінюється заданий кут в другому 90 градусів - коли однакова висота немає сенсу, адже це буде просте з'єднання
-якщо не паралельні і не під 90 градусів, - в елемент, який був обраний першми, буде вставляться фітинг з заданим кутом
