### ISSUE TITLE
Button to generate conduit  Schedule file in Excel format. New Excel File

### ISSUE THREAD

**Issue by StudyCenterParametric** [StudyCenterParametric/VDC_Conduits#39]
![image](https://user-images.githubusercontent.com/102672070/165121382-c6be04ed-e7e8-4ecb-a6d9-79fe197c0052.png)

**Comment by MariyanSlesar** [comment]
-юзер натискає кнопку
-юзер не обирає файл для Екселю
-Ексель файл сам створюється згідно Drafting View
