### ISSUE TITLE
Auto add Conduit ID during first link EXCEL file

### ISSUE THREAD

**Issue by StudyCenterParametric** [StudyCenterParametric/VDC_Conduits#40]
![image](https://user-images.githubusercontent.com/102672070/165126691-e2ef2bc9-1e8d-4bef-ab87-66ec5fce5b0a.png)

**Comment by MariyanSlesar** [comment]
Додаток до команди Sync Conduit Schedule:
 -Auto add Conduit ID during first link
      -коли людина вперше використовує команду Sync Conduit Schedule, параметр Conduit ID автоматично закидуєтсья        в колонку для Revit parameters.
