### ISSUE TITLE
Reset All - видалити всі сліди роботи плагіна.

### ISSUE THREAD

**Issue by StudyCenterParametric** [StudyCenterParametric/VDC_Conduits#42]
![image](https://user-images.githubusercontent.com/102672070/165128764-4148bb5e-6271-4131-a24a-6b4b3e233ffe.png)

**Comment by StudyCenterParametric** [comment]
Захист від дурня. Попередження про наслідки.

**Comment by StudyCenterParametric** [comment]
Видалити ВСІ ДАНІ.
Видалити ВСІ ПАРАМЕТРИ І ДАНІ.
Видалити ВСІ ПАРАМЕТРИ, ДАНІ, Drafting Views.

**Comment by MariyanSlesar** [comment]
-юзер натискає на кнопку
-перед ним вспливає вікно і будуть 3 вибори:
	-видалити дані
	-видалити параметри + дані
	-видалити всі параметри + дані + drafting views
